### ISSUE TITLE
can not locate module XXX

### ISSUE THREAD

**Issue by KES777** [oschwald/SublimeLinter-perl#7]
I have modules installed into home directory.
Linting from sublime I get:
Can't locate Modern/Perl.pm in @INC (you may need to install the Modern::Perl module) (@INC contains: /etc/perl /usr/local/lib/perl/5.18.2 /usr/local/share/perl/5.18.2 /usr/lib/perl5 /usr/share/perl5 /usr/lib/perl/5.18 /usr/share/perl/5.18 /usr/local/lib/site_perl .) at - line 3.

In my shell I set up:
PERL_MB_OPT="--install_base \"/home/user/perl5\""; export PERL_MB_OPT;
PERL_MM_OPT="INSTALL_BASE=/home/user/perl5"; export PERL_MM_OPT;

PERL5LIB='/home/user/perl5/lib/perl5'; export PERL5LIB;

From shell everything works ok, but linting from sublimetext does not see that option, i think.
Please add documentation, to resolve this issue

**Comment by oschwald** [comment]
You can use the existing `include_dirs` option mentioned in the documentation. Alternatively, you could set the environment variables in your launcher for Sublime (or start Sublime from the shell).

**Comment by KES777** [comment]
But I export those env in .bashrc and .bash_profile.
Doc says: The list of shells supported by SublimeLinter is bash.
doing: 
SublimeLinter: perl: tmp.pl ['/usr/bin/perl', '-e while(my($key,$value)=each(%ENV)){warn "$key -> $value\n"}'] 
I saw: SHELL -> /bin/bash
but I do not see any PERL5LIB, PERL_MM_OPT env variables

**Comment by oschwald** [comment]
If you are not able to set the environment variables that Sublime uses (which works fine for me), please use the `include_dirs` option I previously mentioned.

**Comment by KES777** [comment]
I were trying to understand, why do not work that that described in documentation.

on other side, that is unclear how to use include_dirs: which file edit and where to put this option.

**Comment by KES777** [comment]
This issue is related to desctop ubuntu :-/
http://stackoverflow.com/questions/28940230/sublime-does-not-see-env-variables?noredirect=1#comment46135870_28940230
